export const accounts = [
  { id: 1, name: "Bank", default: "dr" },
  { id: 2, name: "Bank OD/CC A/c", default: "dr" },
  { id: 3, name: "Capital", default: "cr" },
  { id: 4, name: "Cash", default: "dr" },
  { id: 5, name: "Creditors", default: "cr" },
  { id: 6, name: "Current Assets", default: "dr" },
  { id: 7, name: "Current Liabilities", default: "cr" },
  { id: 8, name: "Debtors", default: "dr" },
  { id: 9, name: "Deposits - Assets", default: "dr" },
  { id: 10, name: "Direct Expense", default: "dr" },
  { id: 11, name: "Direct Income", default: "cr" },
  { id: 12, name: "Duties & Taxes", default: "cr" },
  { id: 13, name: "Fixed Asset", default: "dr" },
  { id: 14, name: "Indirect Expense", default: "dr" },
  { id: 15, name: "Indirect Income", default: "cr" },
  { id: 16, name: "Investments", default: "dr" },
  { id: 17, name: "Loans and Advances - Asset", default: "dr" },
  { id: 18, name: "Miscellaneous Assets", default: "dr" },
  { id: 19, name: "Miscellaneous Liabilities", default: "cr" },
  { id: 20, name: "Provisions", default: "cr" },
  { id: 21, name: "Purchases", default: "dr" },
  { id: 22, name: "Reserves", default: "cr" },
  { id: 23, name: "Sales", default: "cr" },
  { id: 24, name: "Secured Loan", default: "cr" },
  { id: 25, name: "Stock", default: "dr" },
  { id: 26, name: "Suspense", default: "dr" },
  { id: 27, name: "Unsecured Loan", default: "cr" },
];
